# See dos how to configure the bundle: https://symfony.com/doc/current/bundles/LiipImagineBundle/basic-usage.html
liip_imagine:
  messenger: true
  cache: profile_photos
  resolvers:
    profile_photos:
      web_path:
        # use %kernel.project_dir%/web for Symfony prior to 4.0.0
        web_root: "%%kernel.project_dir%/web"
        cache_prefix: "media/cache"
  filter_sets:
    cache: ~
    thumb:
      cache: profile_photos
      quality: 20