vich_uploader:
  db_driver: orm
  metadata:
    type: attribute
  mappings:
    backgroundRecipe:
      uri_prefix: /img/uploads/background/recipes
      upload_destination: '%kernel.project_dir%/public/img/uploads/background/recipes'
    pictureRecipe:
      uri_prefix: ""
      upload_destination: '%kernel.project_dir%/public/img/uploads/pictures/recipes'
